---
title: "Test speed-up and scale-up of R-Rerf Iteration 8"
author: "James Browne"
date: "May 16 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message=FALSE, cache = FALSE)
library(ggplot2)
nTimes <-20
leg <- theme(legend.text = element_text(size = 12), legend.title=element_blank(), plot.title = element_text(size = 16,  face="bold"), plot.subtitle = element_text(size = 12),axis.title.x = element_text(size=12), axis.text.x = element_text(size=12), axis.title.y = element_text(size=12), axis.text.y = element_text(size=12))
```
**********************************************************************
#### Loading the images and labels
**********************************************************************
```{r LoadView, cache = FALSE}
#Size of the labels is 1 whereas everything else is 4
#Open and position the image file
image_block <- file("../../../data/ubyte/train-images-idx3-ubyte", "rb")
q <- readBin(image_block, integer(), n=1, endian="big")
num_images <- readBin(image_block, integer(), n=1, endian="big")
num_col <- readBin(image_block, integer(), n=1, endian="big")
num_row <- readBin(image_block, integer(), n=1, endian="big")

#Open and position the label file
label_block = file("../../../data/ubyte/train-labels-idx1-ubyte", "rb")
q <- readBin(label_block, integer(), n=1, endian="big")
num_labels <- readBin(label_block, integer(), n=1, endian="big")

X <- readBin(image_block, integer(), n=num_images*num_col*num_row, size=1, signed=FALSE)
X <- matrix(X, ncol=num_col*num_row, byrow=TRUE)

Y <- as.numeric(readBin(label_block, integer(), n=num_labels, size=1, signed=FALSE)+1)

close(image_block)
close(label_block)
gc()

numS<-20000
data_size_curr <- (object.size(X[1:numS,])+object.size(Y[1:numS]))/1000000
```


```{r speed_up_print, cache = FALSE}
load(file="exp0002speedUp.Rdata")
lab <- labs(title="R-RerF Strong Scaling", x="Number of Cores", y="Relative Performance", subtitle =paste("Dataset Size: ", data_size_curr, "MB"))
print(ggplot(ress1,aes(x=Cores_Used, y=Speed_Up, group=Line_Type, color=Line_Type))+geom_line()+lab +leg +scale_y_continuous(trans = "log2", breaks = c(1,2,4,8,16,32)))
```

```{r scale-up-n_print, cache = FALSE}
    load(file="exp0002scaleUp.Rdata")
Tics <- scale_y_continuous(breaks=c(0.0,0.5,1.0),labels=c(0.0,0.5,1.0))
print(ggplot(ress2,aes(x=Cores_Used, y=Scale_Up, group=Line_Type, color=Line_Type))+geom_line()+labs(title="R-RerF Weak Scaling", x="Number of Cores", y="Relative Performance", subtitle=paste("Initial number of samples: 2500 -- Ideal assumes average case complexity"))+expand_limits(y=c(0,1))+leg)
```
