---
title: "Test speed-up and scale-up of R-Rerf Iteration 8"
author: "James Browne"
date: "May 16 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message=FALSE, cache = FALSE)
##source('rfr_function.R')
library(ggplot2)
nTimes <- 20
run_su <- TRUE
num_trees <- 384  
ML <- 6
entry <-1
line_type <- NA
cores_used <- NA
median_time <- NA
speed_up <- NA
ahmdalNum <- NA
ahmdalAlg <- NA
leg <- theme(legend.text = element_text(size = 12), legend.title=element_blank(), plot.title = element_text(size = 16,  face="bold"), plot.subtitle = element_text(size = 12),axis.title.x = element_text(size=12), axis.text.x = element_text(size=12), axis.title.y = element_text(size=12), axis.text.y = element_text(size=12))
```
```{r LoadView, cache = FALSE}
#Size of the labels is 1 whereas everything else is 4
#Open and position the image file
image_block <- file("../../data/ubyte/train-images-idx3-ubyte", "rb")
q <- readBin(image_block, integer(), n=1, endian="big")
num_images <- readBin(image_block, integer(), n=1, endian="big")
num_col <- readBin(image_block, integer(), n=1, endian="big")
num_row <- readBin(image_block, integer(), n=1, endian="big")

#Open and position the label file
label_block = file("../../data/ubyte/train-labels-idx1-ubyte", "rb")
q <- readBin(label_block, integer(), n=1, endian="big")
num_labels <- readBin(label_block, integer(), n=1, endian="big")

X <- readBin(image_block, integer(), n=num_images*num_col*num_row, size=1, signed=FALSE)
X <- matrix(X, ncol=num_col*num_row, byrow=TRUE)

Y <- as.numeric(readBin(label_block, integer(), n=num_labels, size=1, signed=FALSE)+1)

close(image_block)
close(label_block)

image_block <- file("../../data/ubyte/t10k-images-idx3-ubyte", "rb")
q <- readBin(image_block, integer(), n=1, endian="big")
num_images <- readBin(image_block, integer(), n=1, endian="big")
num_col <- readBin(image_block, integer(), n=1, endian="big")
num_row <- readBin(image_block, integer(), n=1, endian="big")

#Open and position the label file
label_block = file("../../data/ubyte/t10k-labels-idx1-ubyte", "rb")
q <- readBin(label_block, integer(), n=1, endian="big")
num_labels <- readBin(label_block, integer(), n=1, endian="big")

Xt <- readBin(image_block, integer(), n=num_images*num_col*num_row, size=1, signed=FALSE)
Xt <- matrix(X, ncol=num_col*num_row, byrow=TRUE)

Yt <- as.numeric(readBin(label_block, integer(), n=num_labels, size=1, signed=FALSE)+1)

close(image_block)
close(label_block)

gc()

NameResults <- "MNIST"
Results <- NULL
Alg <- NULL
```

```{r speed_up_MNIST, cache = FALSE}
if(TRUE){
#create impossible dataset
initial_run_entry<-entry
library(rerf)
		for (p in 2:ML){
		q <- 2^(p-1)
		ptm_hold <- NA
		forest_hold <- NA
		for (i in 1:nTimes){
			gc()
			forest <- RerF(X,Y, trees=num_trees, bagging=.3, min.parent=1, max.depth=6, store.oob=TRUE, stratify=TRUE, num.cores=48, seed=sample(1:100000,1))
			ptm <- proc.time()
predictions <- Predict(Xt, forest, num.cores = q)
     error.rate <- sum(predictions != Yt)/length(Yt)
			ptm_hold[i] <- (proc.time() - ptm)[3]
			forest[i] <- object.size(forest)
		}
		line_type[entry]<-"MNIST"
		cores_used[entry] <- q
		median_time[entry]<- median(ptm_hold)
		speed_up[entry]<-2*median_time[initial_run_entry]/median_time[entry]
        entry<-entry+1
	}

q <- 48
ptm_hold <- NA
		forest_hold <- NA
		for (i in 1:nTimes){
			gc()
			forest <- RerF(X,Y, trees=num_trees, bagging=.3, min.parent=1, max.depth=6, store.oob=TRUE, stratify=TRUE, num.cores=48)
			ptm <- proc.time()
predictions <- Predict(Xt, forest, num.cores =q)
     error.rate <- sum(predictions != Yt)/length(Yt)
			ptm_hold[i] <- (proc.time() - ptm)[3]
			forest[i] <- object.size(forest)
		}
		line_type[entry]<-"MNIST"
		cores_used[entry] <- q
		median_time[entry]<- median(ptm_hold)
		speed_up[entry]<- 2*median_time[initial_run_entry]/median_time[entry]
        entry<-entry+1

cat("MNIST Ah calc") 
currAh <- 0
for(t in 1:(ML-1)){
cat("Amdahl's Number: ", 2-2/((median_time[initial_run_entry+currAh])/(median_time[initial_run_entry+currAh+1])), "\n")
currAh<- currAh + 1
}
ahmdalNum <- c(ahmdalNum, (2-2/((median_time[initial_run_entry+3])/(median_time[initial_run_entry+4]))))
ahmdalAlg <- c(ahmdalAlg, "MNIST")
cat("training times: ", median_time, "\n")
}
```

```{r speed_up_ideal, cache = FALSE}
initial_run_entry<-entry
base <- 256
for (p in 2:ML){
	q<- 2^(p-1)
	line_type[entry]<-"Ideal"
	cores_used[entry] <- q
	median_time[entry]<- base 
	speed_up[entry]<- q
    entry<-entry+1
    base <- base / 2
}
base <- base*1.5
q<- 48
	line_type[entry]<-"Ideal"
	cores_used[entry] <- q
	median_time[entry]<-2 
	speed_up[entry]<- q
    entry<-entry+1

cat("ideal Ah calc") 
currAh <- 0
for(t in 1:(ML-1)){
cat("Amdahl's Number: ", 2-2/((median_time[initial_run_entry+currAh])/(median_time[initial_run_entry+currAh+1])), "\n")
currAh<- currAh + 1
}
ahmdalNum <- c(ahmdalNum, (2-2/((median_time[initial_run_entry+3])/(median_time[initial_run_entry+4]))))
ahmdalAlg <- c(ahmdalAlg, "Ideal")
cat("training times: ", median_time, "\n")
```

**********************************************************************
#### Loading Higgs
**********************************************************************
```{r LoadViewHiggs, cache = FALSE}
mydata <- read.csv(file="../../data/higgs/training.csv", header=TRUE, sep=",")
X <- as.matrix(mydata[,2:31])
Y <- as.numeric(mydata[,33])
#mydata <- read.csv(file="../../data/higgs/test.csv", header=TRUE, sep=",")
#Xt <- as.matrix(mydata[,2:32])
#Yt <- as.numeric(mydata[,33])
mydata <- NA
gc()

NameResults <- c(NameResults, "Higgs")
Results <- NULL
Alg <- NULL
```

```{r speed_Higgs, cache = FALSE}
#create impossible dataset
initial_run_entry<-entry
if(run_su){
		for (p in 2:ML){
		q <- 2^(p-1)
		ptm_hold <- NA
		forest_hold <- NA
		for (i in 1:nTimes){
			gc()

X1 <- sample(1:length(Y[Y==1]), .8 *length(Y[Y==1]), replace=FALSE)
            X2 <- sample(1:length(Y[Y==2]), .8 *length(Y[Y==2]), replace=FALSE)
            Xtr <- rbind(X[Y==1,][X1,],X[Y==2,][X2,])
            Ytr <- c(Y[Y==1][X1], Y[Y==2][X2])
Xte <- rbind(X[Y==1,][-X1,],X[Y==2,][-X2,])
            Yte <- c(Y[Y==1][-X1], Y[Y==2][-X2])

			gc()
			forest <- RerF(Xtr,Ytr, trees=num_trees, bagging=.3, min.parent=1, max.depth=0, store.oob=TRUE, stratify=TRUE, num.cores=48,seed=sample(1:100000,1))
            for( q in 1:num_trees){
m <- which(is.na(forest$trees[[q]]$ClassProb))
forest$trees[[q]]$ClassProb[m] <- .5
            }
			ptm <- proc.time()
predictions <- Predict(Xte, forest, num.cores =q)
     error.rate <- sum(predictions != Yte)/length(Yte)
			ptm_hold[i] <- (proc.time() - ptm)[3]
		}
		line_type[entry]<-"Higgs"
		cores_used[entry] <- q
		median_time[entry]<- median(ptm_hold)
		speed_up[entry]<-2*median_time[initial_run_entry]/median_time[entry]
        entry<-entry+1
	}

q <- 48
		ptm_hold <- NA
		forest_hold <- NA
		for (i in 1:nTimes){
X1 <- sample(1:length(Y[Y==1]), .8 *length(Y[Y==1]), replace=FALSE)
            X2 <- sample(1:length(Y[Y==2]), .8 *length(Y[Y==2]), replace=FALSE)
            Xtr <- rbind(X[Y==1,][X1,],X[Y==2,][X2,])
            Ytr <- c(Y[Y==1][X1], Y[Y==2][X2])
Xte <- rbind(X[Y==1,][-X1,],X[Y==2,][-X2,])
            Yte <- c(Y[Y==1][-X1], Y[Y==2][-X2])

			gc()
			forest <- RerF(Xtr,Ytr, trees=num_trees, bagging=.3, min.parent=1, max.depth=0, store.oob=TRUE, stratify=TRUE, num.cores=48,seed=sample(1:100000,1))
            for( q in 1:num_trees){
m <- which(is.na(forest$trees[[q]]$ClassProb))
forest$trees[[q]]$ClassProb[m] <- .5
            }
			ptm <- proc.time()
predictions <- Predict(Xte, forest, num.cores =q)
     error.rate <- sum(predictions != Yte)/length(Yte)
			ptm_hold[i] <- (proc.time() - ptm)[3]
		}
		line_type[entry]<-"Higgs"
		cores_used[entry] <- q
		median_time[entry]<- median(ptm_hold)
		speed_up[entry]<-2*median_time[initial_run_entry]/median_time[entry]
        entry<-entry+1

cat("Higgs Ah calc") 
currAh <- 0
for(t in 1:(ML-1)){
cat("Amdahl's Number: ", 2-2/((median_time[initial_run_entry+currAh])/(median_time[initial_run_entry+currAh+1])), "\n")
currAh<- currAh + 1
}
ahmdalNum <- c(ahmdalNum, (2-2/((median_time[initial_run_entry+3])/(median_time[initial_run_entry+4]))))
ahmdalAlg <- c(ahmdalAlg, "Higgs")
cat("training times: ", median_time, "\n")
}
```
```{r LoadViewp53, cache = FALSE}
mydata <- read.csv(file="../../data/p53.csv", header=TRUE, sep=",")
X <- as.matrix(mydata[,1:(ncol(mydata)-1)])
Y <- as.numeric(mydata[,ncol(mydata)])
mydata <- NA
gc()

NameResults <- c(NameResults, "p53")
Results <- NULL
Alg <- NULL
```

```{r speed_up_p53, cache = FALSE}
#create impossible dataset
initial_run_entry<-entry
gc()
		for (p in 2:ML){
		q <- 2^(p-1)
		ptm_hold <- NA
		forest_hold <- NA
		for (i in 1:nTimes){
X1 <- sample(1:length(Y[Y==1]), .8 *length(Y[Y==1]), replace=FALSE)
            X2 <- sample(1:length(Y[Y==2]), .8 *length(Y[Y==2]), replace=FALSE)
            Xtr <- rbind(X[Y==1,][X1,],X[Y==2,][X2,])
            Ytr <- c(Y[Y==1][X1], Y[Y==2][X2])
Xte <- rbind(X[Y==1,][-X1,],X[Y==2,][-X2,])
            Yte <- c(Y[Y==1][-X1], Y[Y==2][-X2])
			gc()
			forest <- RerF(Xtr,Ytr, trees=num_trees, bagging=.3, min.parent=1, max.depth=0, store.oob=TRUE, stratify=TRUE, num.cores=48,seed=sample(1:100000,1))
			ptm <- proc.time()
predictions <- Predict(Xte, forest, num.cores =q)
     error.rate <- sum(predictions != Yte)/length(Yte)
			ptm_hold[i] <- (proc.time() - ptm)[3]
		}
		line_type[entry]<-"p53"
		cores_used[entry] <- q
		median_time[entry]<- median(ptm_hold)
		speed_up[entry]<-2*median_time[initial_run_entry]/median_time[entry]
        entry<-entry+1
	}

		q <- 48
		ptm_hold <- NA
		forest_hold <- NA
		for (i in 1:nTimes){
X1 <- sample(1:length(Y[Y==1]), .8 *length(Y[Y==1]), replace=FALSE)
            X2 <- sample(1:length(Y[Y==2]), .8 *length(Y[Y==2]), replace=FALSE)
            Xtr <- rbind(X[Y==1,][X1,],X[Y==2,][X2,])
            Ytr <- c(Y[Y==1][X1], Y[Y==2][X2])
Xte <- rbind(X[Y==1,][-X1,],X[Y==2,][-X2,])
            Yte <- c(Y[Y==1][-X1], Y[Y==2][-X2])
			gc()
			forest <- RerF(Xtr,Ytr, trees=num_trees, bagging=.3, min.parent=1, max.depth=0, store.oob=TRUE, stratify=TRUE, num.cores=48,seed=sample(1:100000,1))
			ptm <- proc.time()
predictions <- Predict(Xte, forest, num.cores =q)
     error.rate <- sum(predictions != Yte)/length(Yte)
			ptm_hold[i] <- (proc.time() - ptm)[3]
					}
		line_type[entry]<-"p53"
		cores_used[entry] <- q
		median_time[entry]<- median(ptm_hold)
		speed_up[entry]<-2*median_time[initial_run_entry]/median_time[entry]
        entry<-entry+1

        cat("p53 Ah calc") 
currAh <- 0
for(t in 1:(ML-1)){
cat("Amdahl's Number: ", 2-2/((median_time[initial_run_entry+currAh])/(median_time[initial_run_entry+currAh+1])), "\n")
currAh<- currAh + 1
}
ahmdalNum <- c(ahmdalNum, (2-2/((median_time[initial_run_entry+3])/(median_time[initial_run_entry+4]))))
ahmdalAlg <- c(ahmdalAlg, "p53")
cat("training times: ", median_time, "\n")
```

```{r speed_up_print, cache = FALSE}

ress1<-data.frame(Line_Type=as.factor(line_type), Cores_Used = cores_used, Time_Sec=median_time, Speed_Up=speed_up)
amCal <- data.frame(Algorithm=as.factor(ahmdalAlg), Anum=ahmdalNum)
save(ress1, file="exp0039.Rdata")
save(amCal, file="exp0039Anum.Rdata")
flush.console()

lab <- labs(title="Testing Time Strong Scaling", x="Number of Cores", y="Relative Performance")
print(ggplot(ress1,aes(x=Cores_Used, y=Speed_Up, group=Line_Type, color=Line_Type))+geom_line()+lab +leg+geom_text(x = 15, y =40 , label =paste("Amdahl Number\nMNIST: ",signif(amCal[2,2], digits=2),"\nHiggs: ", signif(amCal[4,2], digits=2), "\np53: ", signif(amCal[5,2],digits=2))))
```
