# ---
# title: "Test speed-up and scale-up of R-Rerf against xg and ranger"
# author: "James Browne"
# date: "Oct 10 2017"
# output: html_document
# ---

pWidth = 300
pHeight = 300
tWidth = pWidth * .05
tHeight = .10 * pHeight
library(ggplot2)
leg <- theme(legend.text = element_text(size = 12), legend.title=element_blank(), plot.title = element_text(size = 16,  face="bold"), plot.subtitle = element_text(size = 12),axis.title.x = element_text(size=12), axis.text.x = element_text(size=12), axis.title.y = element_text(size=12), axis.text.y = element_text(size=12))

load(file="exp0039.Rdata")
load(file="exp0039Anum.Rdata")

lab <- labs(title="Testing Time Strong Scaling", x="Number of Cores", y="Relative Performance")
png(file="exp0039.png", width=300, height=300)
print(ggplot(ress1,aes(x=Cores_Used, y=Speed_Up, group=Line_Type, color=Line_Type))+geom_line()+lab +xlim(0,50) +leg+geom_text(x = tWidth, y =tHeight , label =paste("Amdahl Number\nMNIST: ",signif(amCal[2,2], digits=2),"\nHiggs: ", signif(amCal[4,2], digits=2), "\np53: ", signif(amCal[5,2],digits=2))))
dev.off()

