---
title: "Test speed of breadth vs depth, exp0010"
author: "James Browne"
date: "July 06, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message=FALSE, cache = FALSE)
nTimes<-2
#Required for below sections
line_type <- NA
cores_used <- NA
speed_up <- NA
median_time <- NA
num_samples <- NA
entry <- 1L
core_num <- 1
num_trees <- 1
ptm_hold <-NA 
initial <- 30000
step <- 10000 #should be 5000
numC <- 784
numR <- 60000
final <-numR
run_print <- TRUE
```

**********************************************************************
Print
**********************************************************************
```{r load_print, cache = FALSE}

library(ggplot2)
for (p in 1:6){
	q<- 2^(p-1)
	line_type[entry]<-"Ideal"
	cores_used[entry] <- q
	median_time[entry]<-2 
	speed_up[entry]<- q
    entry<-entry+1
}

ress1 <- data.frame(Line_Type=as.factor(line_type), Cores_Used = as.factor(cores_used), Time_Sec=median_time, Speed_Up=speed_up)

  if (file.exists("data/brfr.Rdata")){
  load(file = "data/brfr.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }
if (file.exists("data/dlrfr.Rdata")){
  load(file = "data/dlrfr.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }
if (file.exists("data/dbrfr.Rdata")){
  load(file = "data/dbrfr.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }
if (file.exists("data/dsrfr.Rdata")){
  load(file = "data/dsrfr.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }


if (file.exists("data/brfrRow.Rdata")){
  load(file = "data/brfrRow.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }
if (file.exists("data/dlrfrRow.Rdata")){
  load(file = "data/dlrfrRow.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }
if (file.exists("data/dbrfrRow.Rdata")){
  load(file = "data/dbrfrRow.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }
if (file.exists("data/dsrfrRow.Rdata")){
  load(file = "data/dsrfrRow.Rdata")
  ress1 <- rbind(ress1, res_brfr) 
  }
```

```{r print, cache = FALSE}
  leg <- theme(legend.text = element_text(size = 12), legend.title=element_blank(), plot.title = element_text(size = 16,  face="bold"), plot.subtitle = element_text(size = 12),axis.title.x = element_text(size=12), axis.text.x = element_text(size=12), axis.title.y = element_text(size=12), axis.text.y = element_text(size=12))

lab <- labs(title="R-RerF Speed-up on MNIST", x="Number of Cores", y="Relative Performance", subtitle =paste("MNIST[60000x784], 10 classes\ndataset size: 160MB"))

print(ggplot(ress1,aes(x=Cores_Used, y=Speed_Up, group=Line_Type, color=Line_Type))+geom_line()+lab +leg +scale_y_continuous(trans = "log2", breaks = c(1,2,4,8,16,32)))
```

