---
title: "Test speed of breadth vs depth, exp0001"
author: "James Browne"
date: "June 22, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message=FALSE, cache = FALSE)
```
**********************************************************************
Print
**********************************************************************
```{r print, cache = FALSE}
    load("0001results.Rdata")
library(ggplot2)
leg <- theme(legend.text = element_text(size = 12), legend.title=element_blank(), plot.title = element_text(size = 16,  face="bold"), plot.subtitle = element_text(size = 12),axis.title.x = element_text(size=12), axis.text.x = element_text(size=12), axis.title.y = element_text(size=12), axis.text.y = element_text(size=12))
lab <- labs(title="Breadth vs Depth Speed", x="Number of Samples", y="Training Time (s)")
print(ggplot(ress1,aes(x=Num_Samples, y=Time_Sec, group=Line_Type, color=Line_Type))+geom_line()+lab +leg+scale_y_continuous(trans = "log10"))
```
